name: passenger_app
description: "SafeDriver Passenger App - A comprehensive safety-focused transportation application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296

  # State Management
  provider: ^6.1.2
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Firebase Services
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  google_sign_in: ^6.2.1

  # Location & Maps
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  geocoding: ^2.1.1
  location: ^5.0.3

  # QR Code Scanner
  mobile_scanner: ^3.5.6
  qr_flutter: ^4.1.0

  # Media & Camera
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  video_player: ^2.8.1

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # Network & HTTP
  http: ^1.1.2
  dio: ^5.4.0
  connectivity_plus: ^5.0.2

  # Permissions
  permission_handler: ^11.1.0

  # UI Components & Charts
  fl_chart: ^0.66.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  lottie: ^2.7.0

  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0

  # Encryption & Security
  crypto: ^3.0.3
  encrypt: ^5.0.3

  # Biometrics
  local_auth: ^2.1.7

  # Push Notifications
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4

  # Forms & Validation
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
