// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcibaYhXUItkAhrUQuugWyDirmQ3-0VfY',
    appId: '1:719842751658:web:your_web_app_id',
    messagingSenderId: '719842751658',
    projectId: 'safe-driver-system',
    authDomain: 'safe-driver-system.firebaseapp.com',
    storageBucket: 'safe-driver-system.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcibaYhXUItkAhrUQuugWyDirmQ3-0VfY',
    appId: '1:719842751658:android:c1b794fb9edad4d2514cd3',
    messagingSenderId: '719842751658',
    projectId: 'safe-driver-system',
    storageBucket: 'safe-driver-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcibaYhXUItkAhrUQuugWyDirmQ3-0VfY',
    appId: '1:719842751658:ios:your_ios_app_id',
    messagingSenderId: '719842751658',
    projectId: 'safe-driver-system',
    storageBucket: 'safe-driver-system.firebasestorage.app',
    iosBundleId: 'com.example.passengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcibaYhXUItkAhrUQuugWyDirmQ3-0VfY',
    appId: '1:719842751658:ios:your_macos_app_id',
    messagingSenderId: '719842751658',
    projectId: 'safe-driver-system',
    storageBucket: 'safe-driver-system.firebasestorage.app',
    iosBundleId: 'com.example.passengerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcibaYhXUItkAhrUQuugWyDirmQ3-0VfY',
    appId: '1:719842751658:web:your_windows_app_id',
    messagingSenderId: '719842751658',
    projectId: 'safe-driver-system',
    authDomain: 'safe-driver-system.firebaseapp.com',
    storageBucket: 'safe-driver-system.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}
